[theme]
base = "dark"
backgroundColor = "#23263D"
secondaryBackgroundColor = "#292C48"
textColor = "#EEEFF7"
primaryColor = "#EF6603"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false